Load factorio setting on startup

diff --git a/infra/factorio/init.sh.tmpl b/infra/factorio/init.sh.tmpl
--- a/infra/factorio/init.sh.tmpl
+++ b/infra/factorio/init.sh.tmpl
@@ -15,12 +15,17 @@ if [ ! "xfs" = "$FS_TYPE" ]; then
   mkfs -t xfs "$DEV_PATH"
 fi
 
-if ! mount | grep "/opt/factorio_saves"; then
-  mkdir -p /opt/factorio_saves
+if ! mount | grep "/opt/factorio/saves"; then
+  mkdir -p /opt/factorio/saves
   UUID=$(blkid "$DEV_PATH" | grep -oP 'UUID="\K([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})')
-  FSTAB_LINE=$(printf "UUID=%s  /opt/factorio_saves  xfs  defaults,nofail  0  2" "$UUID")
+  FSTAB_LINE=$(printf "UUID=%s  /opt/factorio/saves  xfs  defaults,nofail  0  2" "$UUID")
   echo "$FSTAB_LINE" >> /etc/fstab
   mount -a
-  chown -R factorio:factorio /opt/factorio_saves
-  chmod -R g+rwx /opt/factorio_saves
+  chown -R factorio:factorio /opt/factorio/saves
+  chmod -R g+rwx /opt/factorio/saves
 fi
+
+mkdir -p /etc/factorio
+chown -R factorio:factorio /etc/factorio
+chmod -R g+rwx /etc/factorio
+echo "${config_bucket}" >> /etc/factorio/bucket.conf
